# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_date', models.DateField()),
                ('detail_text', models.CharField(max_length=200)),
                ('money', models.FloatField(default=0)),
                ('money_type', models.CharField(max_length=8)),
                ('balance', models.FloatField(default=0)),
            ],
        ),
    ]
