# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bi',
            old_name='detail_text',
            new_name='file_name',
        ),
        migrations.RemoveField(
            model_name='bi',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bi',
            name='money',
        ),
        migrations.RemoveField(
            model_name='bi',
            name='money_type',
        ),
        migrations.RemoveField(
            model_name='bi',
            name='save_date',
        ),
    ]
