# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0002_auto_20170418_0610'),
    ]

    operations = [
        migrations.CreateModel(
            name='PivotTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(max_length=20)),
                ('col', models.CharField(max_length=20)),
                ('measure', models.CharField(max_length=20)),
                ('mode', models.IntegerField(default=0)),
            ],
        ),
    ]
