# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0003_pivottable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pivottable',
            old_name='col',
            new_name='dimension',
        ),
        migrations.RenameField(
            model_name='pivottable',
            old_name='row',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='pivottable',
            name='mode',
        ),
    ]
