# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0006_colselect_rowselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measureselect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure', models.CharField(max_length=20)),
            ],
        ),
    ]
