# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0008_fileselect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphselect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subgraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_graph', models.CharField(max_length=20)),
            ],
        ),
    ]
