# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bi', '0009_graphselect_subgraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graphmeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measure_graph', models.CharField(max_length=20)),
            ],
        ),
    ]
